"""initial schema

Revision ID: 8db14bfa0ba6
Revises: 
Create Date: 2026-10-03 23:12:05.682332
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8db14bfa0ba6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runners',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('queues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=300), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', 'user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('repo_full_name', sa.String(length=300), nullable=True),
    sa.Column('default_branch', sa.String(length=200), nullable=True),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=True),
    sa.Column('pr_write_enabled', sa.Boolean(), nullable=False),
    sa.Column('public_share_token', sa.String(length=64), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_share_token')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_index(op.f('ix_projects_repo_full_name'), 'projects', ['repo_full_name'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('adapter', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('metrics_url', sa.Text(), nullable=True),
    sa.Column('secret_name', sa.String(length=100), nullable=True),
    sa.Column('runner_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_org_id'), 'endpoints', ['org_id'], unique=False)
    op.create_index(op.f('ix_endpoints_project_id'), 'endpoints', ['project_id'], unique=False)
    op.create_table('eval_datasets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version')
    )
    op.create_index(op.f('ix_eval_datasets_org_id'), 'eval_datasets', ['org_id'], unique=False)
    op.create_index(op.f('ix_eval_datasets_project_id'), 'eval_datasets', ['project_id'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('blob_key', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_sources_org_id'), 'evidence_sources', ['org_id'], unique=False)
    op.create_index(op.f('ix_evidence_sources_project_id'), 'evidence_sources', ['project_id'], unique=False)
    op.create_table('failure_modes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('capability_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key')
    )
    op.create_index(op.f('ix_failure_modes_org_id'), 'failure_modes', ['org_id'], unique=False)
    op.create_index(op.f('ix_failure_modes_project_id'), 'failure_modes', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('queue', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['queue', 'status', 'run_after'], unique=False)
    op.create_index(op.f('ix_jobs_org_id'), 'jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_table('pr_impacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('check_run_id', sa.BigInteger(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pr_impacts_org_id'), 'pr_impacts', ['org_id'], unique=False)
    op.create_index(op.f('ix_pr_impacts_pr_number'), 'pr_impacts', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pr_impacts_project_id'), 'pr_impacts', ['project_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_org_id'), 'scans', ['org_id'], unique=False)
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_secrets_org_id'), 'secrets', ['org_id'], unique=False)
    op.create_index(op.f('ix_secrets_project_id'), 'secrets', ['project_id'], unique=False)
    op.create_table('app_specs',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index(op.f('ix_app_specs_org_id'), 'app_specs', ['org_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('subject_key', sa.Text(), nullable=False),
    sa.Column('predicate', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('observation', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('conflict_group', sa.String(length=64), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_conflict_group'), 'claims', ['conflict_group'], unique=False)
    op.create_index(op.f('ix_claims_org_id'), 'claims', ['org_id'], unique=False)
    op.create_index(op.f('ix_claims_scan_id'), 'claims', ['scan_id'], unique=False)
    op.create_index('ix_claims_subject_predicate', 'claims', ['scan_id', 'subject_key', 'predicate'], unique=False)
    op.create_table('eval_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_ref', sa.Text(), nullable=True),
    sa.Column('split', sa.String(length=10), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['eval_datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_items_dataset_id'), 'eval_items', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_eval_items_org_id'), 'eval_items', ['org_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['eval_datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_dataset_id'), 'eval_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_org_id'), 'eval_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_eval_runs_project_id'), 'eval_runs', ['project_id'], unique=False)
    op.create_table('evaluators',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('failure_mode_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calibration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', 'version')
    )
    op.create_index(op.f('ix_evaluators_failure_mode_id'), 'evaluators', ['failure_mode_id'], unique=False)
    op.create_index(op.f('ix_evaluators_org_id'), 'evaluators', ['org_id'], unique=False)
    op.create_index(op.f('ix_evaluators_project_id'), 'evaluators', ['project_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=False),
    sa.Column('extractor', sa.String(length=100), nullable=False),
    sa.Column('observation', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_org_id'), 'evidence', ['org_id'], unique=False)
    op.create_index(op.f('ix_evidence_scan_id'), 'evidence', ['scan_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('forge_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patch_blob', sa.Text(), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forge_runs_org_id'), 'forge_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_forge_runs_project_id'), 'forge_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_forge_runs_scan_id'), 'forge_runs', ['scan_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('src_key', sa.Text(), nullable=False),
    sa.Column('dst_key', sa.Text(), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_org_id'), 'graph_edges', ['org_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_project_id'), 'graph_edges', ['project_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_scan_id'), 'graph_edges', ['scan_id'], unique=False)
    op.create_index('ix_graph_edges_scan_src', 'graph_edges', ['scan_id', 'src_key'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'key')
    )
    op.create_index(op.f('ix_graph_nodes_kind'), 'graph_nodes', ['kind'], unique=False)
    op.create_index(op.f('ix_graph_nodes_org_id'), 'graph_nodes', ['org_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_project_id'), 'graph_nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_scan_id'), 'graph_nodes', ['scan_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('msg', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('evidence_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('priority', sa.String(length=2), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_method', sa.Text(), nullable=False),
    sa.Column('node_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forge_action', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_org_id'), 'recommendations', ['org_id'], unique=False)
    op.create_index(op.f('ix_recommendations_scan_id'), 'recommendations', ['scan_id'], unique=False)
    op.create_table('repair_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pr_impact_id', sa.UUID(), nullable=True),
    sa.Column('attempt', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pr_impact_id'], ['pr_impacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_attempts_org_id'), 'repair_attempts', ['org_id'], unique=False)
    op.create_index(op.f('ix_repair_attempts_pr_impact_id'), 'repair_attempts', ['pr_impact_id'], unique=False)
    op.create_index(op.f('ix_repair_attempts_project_id'), 'repair_attempts', ['project_id'], unique=False)
    op.create_index(op.f('ix_repair_attempts_status'), 'repair_attempts', ['status'], unique=False)
    op.create_table('workload_specs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workload_specs_org_id'), 'workload_specs', ['org_id'], unique=False)
    op.create_index(op.f('ix_workload_specs_project_id'), 'workload_specs', ['project_id'], unique=False)
    op.create_index(op.f('ix_workload_specs_scan_id'), 'workload_specs', ['scan_id'], unique=False)
    op.create_table('bench_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workload_spec_id', sa.UUID(), nullable=True),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_blob', sa.Text(), nullable=True),
    sa.Column('telemetry_blob', sa.Text(), nullable=True),
    sa.Column('report_md_blob', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workload_spec_id'], ['workload_specs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bench_runs_org_id'), 'bench_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_bench_runs_project_id'), 'bench_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_bench_runs_status'), 'bench_runs', ['status'], unique=False)
    op.create_index(op.f('ix_bench_runs_workload_spec_id'), 'bench_runs', ['workload_spec_id'], unique=False)
    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('stance', sa.String(length=12), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id')
    )
    op.create_table('eval_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=5), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['evaluators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['eval_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_evaluator_id'), 'eval_results', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_eval_results_item_id'), 'eval_results', ['item_id'], unique=False)
    op.create_index(op.f('ix_eval_results_org_id'), 'eval_results', ['org_id'], unique=False)
    op.create_index(op.f('ix_eval_results_run_id'), 'eval_results', ['run_id'], unique=False)
    op.create_table('human_labels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('failure_mode_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=4), nullable=False),
    sa.Column('labeler', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['eval_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'failure_mode_id', 'labeler')
    )
    op.create_index(op.f('ix_human_labels_failure_mode_id'), 'human_labels', ['failure_mode_id'], unique=False)
    op.create_index(op.f('ix_human_labels_item_id'), 'human_labels', ['item_id'], unique=False)
    op.create_index(op.f('ix_human_labels_org_id'), 'human_labels', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_labels_org_id'), table_name='human_labels')
    op.drop_index(op.f('ix_human_labels_item_id'), table_name='human_labels')
    op.drop_index(op.f('ix_human_labels_failure_mode_id'), table_name='human_labels')
    op.drop_table('human_labels')
    op.drop_index(op.f('ix_eval_results_run_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_org_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_item_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_evaluator_id'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_table('claim_evidence')
    op.drop_index(op.f('ix_bench_runs_workload_spec_id'), table_name='bench_runs')
    op.drop_index(op.f('ix_bench_runs_status'), table_name='bench_runs')
    op.drop_index(op.f('ix_bench_runs_project_id'), table_name='bench_runs')
    op.drop_index(op.f('ix_bench_runs_org_id'), table_name='bench_runs')
    op.drop_table('bench_runs')
    op.drop_index(op.f('ix_workload_specs_scan_id'), table_name='workload_specs')
    op.drop_index(op.f('ix_workload_specs_project_id'), table_name='workload_specs')
    op.drop_index(op.f('ix_workload_specs_org_id'), table_name='workload_specs')
    op.drop_table('workload_specs')
    op.drop_index(op.f('ix_repair_attempts_status'), table_name='repair_attempts')
    op.drop_index(op.f('ix_repair_attempts_project_id'), table_name='repair_attempts')
    op.drop_index(op.f('ix_repair_attempts_pr_impact_id'), table_name='repair_attempts')
    op.drop_index(op.f('ix_repair_attempts_org_id'), table_name='repair_attempts')
    op.drop_table('repair_attempts')
    op.drop_index(op.f('ix_recommendations_scan_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_org_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_graph_nodes_scan_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_project_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_org_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_kind'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index('ix_graph_edges_scan_src', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_scan_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_project_id'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_org_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_forge_runs_scan_id'), table_name='forge_runs')
    op.drop_index(op.f('ix_forge_runs_project_id'), table_name='forge_runs')
    op.drop_index(op.f('ix_forge_runs_org_id'), table_name='forge_runs')
    op.drop_table('forge_runs')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_scan_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_org_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_evaluators_project_id'), table_name='evaluators')
    op.drop_index(op.f('ix_evaluators_org_id'), table_name='evaluators')
    op.drop_index(op.f('ix_evaluators_failure_mode_id'), table_name='evaluators')
    op.drop_table('evaluators')
    op.drop_index(op.f('ix_eval_runs_project_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_org_id'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_dataset_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_eval_items_org_id'), table_name='eval_items')
    op.drop_index(op.f('ix_eval_items_dataset_id'), table_name='eval_items')
    op.drop_table('eval_items')
    op.drop_index('ix_claims_subject_predicate', table_name='claims')
    op.drop_index(op.f('ix_claims_scan_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_org_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_conflict_group'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_app_specs_org_id'), table_name='app_specs')
    op.drop_table('app_specs')
    op.drop_index(op.f('ix_secrets_project_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_org_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_org_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_pr_impacts_project_id'), table_name='pr_impacts')
    op.drop_index(op.f('ix_pr_impacts_pr_number'), table_name='pr_impacts')
    op.drop_index(op.f('ix_pr_impacts_org_id'), table_name='pr_impacts')
    op.drop_table('pr_impacts')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_org_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_failure_modes_project_id'), table_name='failure_modes')
    op.drop_index(op.f('ix_failure_modes_org_id'), table_name='failure_modes')
    op.drop_table('failure_modes')
    op.drop_index(op.f('ix_evidence_sources_project_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_org_id'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_eval_datasets_project_id'), table_name='eval_datasets')
    op.drop_index(op.f('ix_eval_datasets_org_id'), table_name='eval_datasets')
    op.drop_table('eval_datasets')
    op.drop_index(op.f('ix_endpoints_project_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_org_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_projects_repo_full_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('webhook_deliveries')
    op.drop_table('users')
    op.drop_table('runners')
    op.drop_table('orgs')
    # ### end Alembic commands ###
